name: bytedance-cv
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pillow
  - tqdm
  - pip:
      - torch
      - torchvision
      - torchaudio
      - opencv-python
      - onnxruntime
      - insightface
      - gdown
      - datasets
      - "huggingface_hub>=0.19,<1.0"
      - transformers==4.37.2
      - reportlab
